export default [
    { id: 1, denomination: 'USD', country: 'United States', sign: '$' },
    { id: 2, denomination: 'EUR', country: 'European Union', sign: '€' },
    { id: 3, denomination: 'JPY', country: 'Japan', sign: '¥' },
    { id: 4, denomination: 'GBP', country: 'United Kingdom', sign: '£' },
    { id: 5, denomination: 'AUD', country: 'Australia', sign: 'A$' },
    { id: 6, denomination: 'CAD', country: 'Canada', sign: 'C$' },
    { id: 7, denomination: 'CHF', country: 'Switzerland', sign: 'Fr' },
    { id: 8, denomination: 'CNY', country: 'China', sign: '¥' },
    { id: 9, denomination: 'INR', country: 'India', sign: '₹' },
    { id: 10, denomination: 'RUB', country: 'Russia', sign: '₽' },
    { id: 11, denomination: 'BRL', country: 'Brazil', sign: 'R$' },
    { id: 12, denomination: 'KRW', country: 'South Korea', sign: '₩' },
    { id: 13, denomination: 'MXN', country: 'Mexico', sign: 'Mex$' },
    { id: 14, denomination: 'NZD', country: 'New Zealand', sign: 'NZ$' },
    { id: 15, denomination: 'SEK', country: 'Sweden', sign: 'kr' },
    { id: 16, denomination: 'NOK', country: 'Norway', sign: 'kr' },
    { id: 17, denomination: 'ZAR', country: 'South Africa', sign: 'R' },
    { id: 18, denomination: 'TRY', country: 'Turkey', sign: '₺' },
    { id: 19, denomination: 'SGD', country: 'Singapore', sign: 'S$' },
    { id: 20, denomination: 'HKD', country: 'Hong Kong', sign: 'HK$' },
];
